# Generated by Django 6.0.2 on 2026-03-18 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=225)),
                ('ptype', models.CharField(max_length=225)),
                ('pprice', models.CharField(max_length=225)),
                ('p_photo', models.ImageField(upload_to='product_photo/')),
                ('pdescription', models.TextField()),
                ('quantity', models.IntegerField()),
                ('total_price', models.CharField(max_length=225)),
                ('order_shipped_status', models.CharField(default='Pending', max_length=225)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindashboard.product')),
            ],
        ),
    ]
