# Generated by Django 6.0.2 on 2026-03-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pname',
            field=models.CharField(default='Unknown', max_length=225),
        ),
    ]
