# Generated by Django 5.2.11 on 2026-03-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('mobile_number', models.BigIntegerField()),
                ('profile_image', models.ImageField(upload_to='profile_images/')),
                ('address', models.TextField(max_length=255)),
            ],
        ),
    ]
